---
- name: Configure Docker yum repository
  template: src='docker.repo.j2' dest='/etc/yum.repos.d/docker.repo'

- name: Install Docker Engine
  yum:
    name: docker-engine
    state: installed

- name: Enable and start docker service
  systemd:
    name: docker
    enabled: yes
    state: started
